apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockpress
  labels:
    app: dockpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dockpress
        environment: production
        type: webserver
    spec:
      spec:
      # nodeSelector:
      #   cloud.google.com/gke-spot: "true"
      volumes:
      - name: tmpfs
        emptyDir:
          sizeLimit: 5Gi
      - name: dockpress-wp-root-nfs-pvc
        persistentVolumeClaim:
          claimName: dockpress-wp-root-nfs-pvc
          readOnly: false
      - name: secret-credentials
        secret:
          secretName: credentials
      containers:
      - image: eu.gcr.io/dockerpress-379014/dockpress/dockpress:latest
        name: dockpress
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            memory: 2048Mi
            cpu: 1000m
            ephemeral-storage: 5Gi
        volumeMounts:
        - name: tmpfs
          mountPath: /tmp
        - name: dockpress-wp-root-nfs-pvc
          mountPath: /var/www/html
        - name: 'secret-credentials'
          mountPath: /secrets
          readOnly: true
        livenessProbe:
          httpGet:
            path: '/'
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 3
status: {}
