apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockpress
  labels:
    app: dockpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dockpress
        environment: production
        type: webserver
    spec:
      volumes:
      - name: dockpress-uploads-nfs-pvc
        persistentVolumeClaim:
          claimName: dockpress-uploads-nfs-pvc
          readOnly: false
      - name: secret-credentials
        secret:
          secretName: credentials
      containers:
      - image: eu.gcr.io/dockerpress-379014/dockpress/dockpress:latest
        name: dockpress
        ports:
          - containerPort: 80
        resources:
          limits:
            ephemeral-storage: 1Gi
            memory: 256Mi
            cpu: 100m
        volumeMounts:
        - name: dockpress-uploads-nfs-pvc
          mountPath: /var/www/html/wp-content/uploads
        - name: 'secret-credentials'
          mountPath: /secrets
          readOnly: true
        livenessProbe:
          httpGet:
            path: '/'
            port: '80'
          initialDelaySeconds: 60
          periodSeconds: 3
status: {}
