apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockpress-uploads-nfs-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /uploads
    server: '10.123.81.66'

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dockpress-uploads-nfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: dockpress-uploads-nfs-pv
  resources:
    requests:
      storage: 100Gi
